/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StaffIndexRouteImport } from './routes/staff.index'
import { Route as StaffSlotsIndexRouteImport } from './routes/staff-slots.index'
import { Route as StaffConstraintsIndexRouteImport } from './routes/staff-constraints.index'
import { Route as StaffAssignmentsIndexRouteImport } from './routes/staff-assignments.index'
import { Route as SchedulesIndexRouteImport } from './routes/schedules.index'
import { Route as ScheduleRequirementsIndexRouteImport } from './routes/schedule-requirements.index'
import { Route as StaffIdRouteImport } from './routes/staff.$id'
import { Route as ApiStaffSlotsRouteImport } from './routes/api.staff-slots'
import { Route as ApiStaffConstraintsRouteImport } from './routes/api.staff-constraints'
import { Route as ApiStaffAssignmentsRouteImport } from './routes/api.staff-assignments'
import { Route as ApiStaffRouteImport } from './routes/api.staff'
import { Route as ApiSchedulesRouteImport } from './routes/api.schedules'
import { Route as ApiScheduleRequirementsRouteImport } from './routes/api.schedule-requirements'
import { Route as DemoStartServerFuncsRouteImport } from './routes/demo/start.server-funcs'
import { Route as DemoStartApiRequestRouteImport } from './routes/demo/start.api-request'
import { Route as DemoApiNamesRouteImport } from './routes/demo/api.names'
import { Route as ApiStaffIdRouteImport } from './routes/api.staff.$id'
import { Route as ApiStaffSlotsIdRouteImport } from './routes/api.staff-slots.$id'
import { Route as ApiStaffConstraintsIdRouteImport } from './routes/api.staff-constraints.$id'
import { Route as ApiStaffAssignmentsIdRouteImport } from './routes/api.staff-assignments.$id'
import { Route as ApiSchedulesIdRouteImport } from './routes/api.schedules.$id'
import { Route as ApiScheduleRequirementsIdRouteImport } from './routes/api.schedule-requirements.$id'
import { Route as DemoStartSsrIndexRouteImport } from './routes/demo/start.ssr.index'
import { Route as DemoStartSsrSpaModeRouteImport } from './routes/demo/start.ssr.spa-mode'
import { Route as DemoStartSsrFullSsrRouteImport } from './routes/demo/start.ssr.full-ssr'
import { Route as DemoStartSsrDataOnlyRouteImport } from './routes/demo/start.ssr.data-only'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/staff/',
  path: '/staff/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffSlotsIndexRoute = StaffSlotsIndexRouteImport.update({
  id: '/staff-slots/',
  path: '/staff-slots/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffConstraintsIndexRoute = StaffConstraintsIndexRouteImport.update({
  id: '/staff-constraints/',
  path: '/staff-constraints/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffAssignmentsIndexRoute = StaffAssignmentsIndexRouteImport.update({
  id: '/staff-assignments/',
  path: '/staff-assignments/',
  getParentRoute: () => rootRouteImport,
} as any)
const SchedulesIndexRoute = SchedulesIndexRouteImport.update({
  id: '/schedules/',
  path: '/schedules/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRequirementsIndexRoute =
  ScheduleRequirementsIndexRouteImport.update({
    id: '/schedule-requirements/',
    path: '/schedule-requirements/',
    getParentRoute: () => rootRouteImport,
  } as any)
const StaffIdRoute = StaffIdRouteImport.update({
  id: '/staff/$id',
  path: '/staff/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStaffSlotsRoute = ApiStaffSlotsRouteImport.update({
  id: '/api/staff-slots',
  path: '/api/staff-slots',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStaffConstraintsRoute = ApiStaffConstraintsRouteImport.update({
  id: '/api/staff-constraints',
  path: '/api/staff-constraints',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStaffAssignmentsRoute = ApiStaffAssignmentsRouteImport.update({
  id: '/api/staff-assignments',
  path: '/api/staff-assignments',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStaffRoute = ApiStaffRouteImport.update({
  id: '/api/staff',
  path: '/api/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSchedulesRoute = ApiSchedulesRouteImport.update({
  id: '/api/schedules',
  path: '/api/schedules',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScheduleRequirementsRoute = ApiScheduleRequirementsRouteImport.update({
  id: '/api/schedule-requirements',
  path: '/api/schedule-requirements',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartServerFuncsRoute = DemoStartServerFuncsRouteImport.update({
  id: '/demo/start/server-funcs',
  path: '/demo/start/server-funcs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartApiRequestRoute = DemoStartApiRequestRouteImport.update({
  id: '/demo/start/api-request',
  path: '/demo/start/api-request',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiNamesRoute = DemoApiNamesRouteImport.update({
  id: '/demo/api/names',
  path: '/demo/api/names',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStaffIdRoute = ApiStaffIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiStaffRoute,
} as any)
const ApiStaffSlotsIdRoute = ApiStaffSlotsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiStaffSlotsRoute,
} as any)
const ApiStaffConstraintsIdRoute = ApiStaffConstraintsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiStaffConstraintsRoute,
} as any)
const ApiStaffAssignmentsIdRoute = ApiStaffAssignmentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiStaffAssignmentsRoute,
} as any)
const ApiSchedulesIdRoute = ApiSchedulesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiSchedulesRoute,
} as any)
const ApiScheduleRequirementsIdRoute =
  ApiScheduleRequirementsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => ApiScheduleRequirementsRoute,
  } as any)
const DemoStartSsrIndexRoute = DemoStartSsrIndexRouteImport.update({
  id: '/demo/start/ssr/',
  path: '/demo/start/ssr/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrSpaModeRoute = DemoStartSsrSpaModeRouteImport.update({
  id: '/demo/start/ssr/spa-mode',
  path: '/demo/start/ssr/spa-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrFullSsrRoute = DemoStartSsrFullSsrRouteImport.update({
  id: '/demo/start/ssr/full-ssr',
  path: '/demo/start/ssr/full-ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrDataOnlyRoute = DemoStartSsrDataOnlyRouteImport.update({
  id: '/demo/start/ssr/data-only',
  path: '/demo/start/ssr/data-only',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/schedule-requirements': typeof ApiScheduleRequirementsRouteWithChildren
  '/api/schedules': typeof ApiSchedulesRouteWithChildren
  '/api/staff': typeof ApiStaffRouteWithChildren
  '/api/staff-assignments': typeof ApiStaffAssignmentsRouteWithChildren
  '/api/staff-constraints': typeof ApiStaffConstraintsRouteWithChildren
  '/api/staff-slots': typeof ApiStaffSlotsRouteWithChildren
  '/staff/$id': typeof StaffIdRoute
  '/schedule-requirements': typeof ScheduleRequirementsIndexRoute
  '/schedules': typeof SchedulesIndexRoute
  '/staff-assignments': typeof StaffAssignmentsIndexRoute
  '/staff-constraints': typeof StaffConstraintsIndexRoute
  '/staff-slots': typeof StaffSlotsIndexRoute
  '/staff': typeof StaffIndexRoute
  '/api/schedule-requirements/$id': typeof ApiScheduleRequirementsIdRoute
  '/api/schedules/$id': typeof ApiSchedulesIdRoute
  '/api/staff-assignments/$id': typeof ApiStaffAssignmentsIdRoute
  '/api/staff-constraints/$id': typeof ApiStaffConstraintsIdRoute
  '/api/staff-slots/$id': typeof ApiStaffSlotsIdRoute
  '/api/staff/$id': typeof ApiStaffIdRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/schedule-requirements': typeof ApiScheduleRequirementsRouteWithChildren
  '/api/schedules': typeof ApiSchedulesRouteWithChildren
  '/api/staff': typeof ApiStaffRouteWithChildren
  '/api/staff-assignments': typeof ApiStaffAssignmentsRouteWithChildren
  '/api/staff-constraints': typeof ApiStaffConstraintsRouteWithChildren
  '/api/staff-slots': typeof ApiStaffSlotsRouteWithChildren
  '/staff/$id': typeof StaffIdRoute
  '/schedule-requirements': typeof ScheduleRequirementsIndexRoute
  '/schedules': typeof SchedulesIndexRoute
  '/staff-assignments': typeof StaffAssignmentsIndexRoute
  '/staff-constraints': typeof StaffConstraintsIndexRoute
  '/staff-slots': typeof StaffSlotsIndexRoute
  '/staff': typeof StaffIndexRoute
  '/api/schedule-requirements/$id': typeof ApiScheduleRequirementsIdRoute
  '/api/schedules/$id': typeof ApiSchedulesIdRoute
  '/api/staff-assignments/$id': typeof ApiStaffAssignmentsIdRoute
  '/api/staff-constraints/$id': typeof ApiStaffConstraintsIdRoute
  '/api/staff-slots/$id': typeof ApiStaffSlotsIdRoute
  '/api/staff/$id': typeof ApiStaffIdRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/schedule-requirements': typeof ApiScheduleRequirementsRouteWithChildren
  '/api/schedules': typeof ApiSchedulesRouteWithChildren
  '/api/staff': typeof ApiStaffRouteWithChildren
  '/api/staff-assignments': typeof ApiStaffAssignmentsRouteWithChildren
  '/api/staff-constraints': typeof ApiStaffConstraintsRouteWithChildren
  '/api/staff-slots': typeof ApiStaffSlotsRouteWithChildren
  '/staff/$id': typeof StaffIdRoute
  '/schedule-requirements/': typeof ScheduleRequirementsIndexRoute
  '/schedules/': typeof SchedulesIndexRoute
  '/staff-assignments/': typeof StaffAssignmentsIndexRoute
  '/staff-constraints/': typeof StaffConstraintsIndexRoute
  '/staff-slots/': typeof StaffSlotsIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/api/schedule-requirements/$id': typeof ApiScheduleRequirementsIdRoute
  '/api/schedules/$id': typeof ApiSchedulesIdRoute
  '/api/staff-assignments/$id': typeof ApiStaffAssignmentsIdRoute
  '/api/staff-constraints/$id': typeof ApiStaffConstraintsIdRoute
  '/api/staff-slots/$id': typeof ApiStaffSlotsIdRoute
  '/api/staff/$id': typeof ApiStaffIdRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/schedule-requirements'
    | '/api/schedules'
    | '/api/staff'
    | '/api/staff-assignments'
    | '/api/staff-constraints'
    | '/api/staff-slots'
    | '/staff/$id'
    | '/schedule-requirements'
    | '/schedules'
    | '/staff-assignments'
    | '/staff-constraints'
    | '/staff-slots'
    | '/staff'
    | '/api/schedule-requirements/$id'
    | '/api/schedules/$id'
    | '/api/staff-assignments/$id'
    | '/api/staff-constraints/$id'
    | '/api/staff-slots/$id'
    | '/api/staff/$id'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/schedule-requirements'
    | '/api/schedules'
    | '/api/staff'
    | '/api/staff-assignments'
    | '/api/staff-constraints'
    | '/api/staff-slots'
    | '/staff/$id'
    | '/schedule-requirements'
    | '/schedules'
    | '/staff-assignments'
    | '/staff-constraints'
    | '/staff-slots'
    | '/staff'
    | '/api/schedule-requirements/$id'
    | '/api/schedules/$id'
    | '/api/staff-assignments/$id'
    | '/api/staff-constraints/$id'
    | '/api/staff-slots/$id'
    | '/api/staff/$id'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  id:
    | '__root__'
    | '/'
    | '/api/schedule-requirements'
    | '/api/schedules'
    | '/api/staff'
    | '/api/staff-assignments'
    | '/api/staff-constraints'
    | '/api/staff-slots'
    | '/staff/$id'
    | '/schedule-requirements/'
    | '/schedules/'
    | '/staff-assignments/'
    | '/staff-constraints/'
    | '/staff-slots/'
    | '/staff/'
    | '/api/schedule-requirements/$id'
    | '/api/schedules/$id'
    | '/api/staff-assignments/$id'
    | '/api/staff-constraints/$id'
    | '/api/staff-slots/$id'
    | '/api/staff/$id'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiScheduleRequirementsRoute: typeof ApiScheduleRequirementsRouteWithChildren
  ApiSchedulesRoute: typeof ApiSchedulesRouteWithChildren
  ApiStaffRoute: typeof ApiStaffRouteWithChildren
  ApiStaffAssignmentsRoute: typeof ApiStaffAssignmentsRouteWithChildren
  ApiStaffConstraintsRoute: typeof ApiStaffConstraintsRouteWithChildren
  ApiStaffSlotsRoute: typeof ApiStaffSlotsRouteWithChildren
  StaffIdRoute: typeof StaffIdRoute
  ScheduleRequirementsIndexRoute: typeof ScheduleRequirementsIndexRoute
  SchedulesIndexRoute: typeof SchedulesIndexRoute
  StaffAssignmentsIndexRoute: typeof StaffAssignmentsIndexRoute
  StaffConstraintsIndexRoute: typeof StaffConstraintsIndexRoute
  StaffSlotsIndexRoute: typeof StaffSlotsIndexRoute
  StaffIndexRoute: typeof StaffIndexRoute
  DemoApiNamesRoute: typeof DemoApiNamesRoute
  DemoStartApiRequestRoute: typeof DemoStartApiRequestRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
  DemoStartSsrDataOnlyRoute: typeof DemoStartSsrDataOnlyRoute
  DemoStartSsrFullSsrRoute: typeof DemoStartSsrFullSsrRoute
  DemoStartSsrSpaModeRoute: typeof DemoStartSsrSpaModeRoute
  DemoStartSsrIndexRoute: typeof DemoStartSsrIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/': {
      id: '/staff/'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff-slots/': {
      id: '/staff-slots/'
      path: '/staff-slots'
      fullPath: '/staff-slots'
      preLoaderRoute: typeof StaffSlotsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff-constraints/': {
      id: '/staff-constraints/'
      path: '/staff-constraints'
      fullPath: '/staff-constraints'
      preLoaderRoute: typeof StaffConstraintsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff-assignments/': {
      id: '/staff-assignments/'
      path: '/staff-assignments'
      fullPath: '/staff-assignments'
      preLoaderRoute: typeof StaffAssignmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedules/': {
      id: '/schedules/'
      path: '/schedules'
      fullPath: '/schedules'
      preLoaderRoute: typeof SchedulesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule-requirements/': {
      id: '/schedule-requirements/'
      path: '/schedule-requirements'
      fullPath: '/schedule-requirements'
      preLoaderRoute: typeof ScheduleRequirementsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/$id': {
      id: '/staff/$id'
      path: '/staff/$id'
      fullPath: '/staff/$id'
      preLoaderRoute: typeof StaffIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/staff-slots': {
      id: '/api/staff-slots'
      path: '/api/staff-slots'
      fullPath: '/api/staff-slots'
      preLoaderRoute: typeof ApiStaffSlotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/staff-constraints': {
      id: '/api/staff-constraints'
      path: '/api/staff-constraints'
      fullPath: '/api/staff-constraints'
      preLoaderRoute: typeof ApiStaffConstraintsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/staff-assignments': {
      id: '/api/staff-assignments'
      path: '/api/staff-assignments'
      fullPath: '/api/staff-assignments'
      preLoaderRoute: typeof ApiStaffAssignmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/staff': {
      id: '/api/staff'
      path: '/api/staff'
      fullPath: '/api/staff'
      preLoaderRoute: typeof ApiStaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/schedules': {
      id: '/api/schedules'
      path: '/api/schedules'
      fullPath: '/api/schedules'
      preLoaderRoute: typeof ApiSchedulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/schedule-requirements': {
      id: '/api/schedule-requirements'
      path: '/api/schedule-requirements'
      fullPath: '/api/schedule-requirements'
      preLoaderRoute: typeof ApiScheduleRequirementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/api-request': {
      id: '/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof DemoStartApiRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/names': {
      id: '/demo/api/names'
      path: '/demo/api/names'
      fullPath: '/demo/api/names'
      preLoaderRoute: typeof DemoApiNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/staff/$id': {
      id: '/api/staff/$id'
      path: '/$id'
      fullPath: '/api/staff/$id'
      preLoaderRoute: typeof ApiStaffIdRouteImport
      parentRoute: typeof ApiStaffRoute
    }
    '/api/staff-slots/$id': {
      id: '/api/staff-slots/$id'
      path: '/$id'
      fullPath: '/api/staff-slots/$id'
      preLoaderRoute: typeof ApiStaffSlotsIdRouteImport
      parentRoute: typeof ApiStaffSlotsRoute
    }
    '/api/staff-constraints/$id': {
      id: '/api/staff-constraints/$id'
      path: '/$id'
      fullPath: '/api/staff-constraints/$id'
      preLoaderRoute: typeof ApiStaffConstraintsIdRouteImport
      parentRoute: typeof ApiStaffConstraintsRoute
    }
    '/api/staff-assignments/$id': {
      id: '/api/staff-assignments/$id'
      path: '/$id'
      fullPath: '/api/staff-assignments/$id'
      preLoaderRoute: typeof ApiStaffAssignmentsIdRouteImport
      parentRoute: typeof ApiStaffAssignmentsRoute
    }
    '/api/schedules/$id': {
      id: '/api/schedules/$id'
      path: '/$id'
      fullPath: '/api/schedules/$id'
      preLoaderRoute: typeof ApiSchedulesIdRouteImport
      parentRoute: typeof ApiSchedulesRoute
    }
    '/api/schedule-requirements/$id': {
      id: '/api/schedule-requirements/$id'
      path: '/$id'
      fullPath: '/api/schedule-requirements/$id'
      preLoaderRoute: typeof ApiScheduleRequirementsIdRouteImport
      parentRoute: typeof ApiScheduleRequirementsRoute
    }
    '/demo/start/ssr/': {
      id: '/demo/start/ssr/'
      path: '/demo/start/ssr'
      fullPath: '/demo/start/ssr'
      preLoaderRoute: typeof DemoStartSsrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/spa-mode': {
      id: '/demo/start/ssr/spa-mode'
      path: '/demo/start/ssr/spa-mode'
      fullPath: '/demo/start/ssr/spa-mode'
      preLoaderRoute: typeof DemoStartSsrSpaModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/full-ssr': {
      id: '/demo/start/ssr/full-ssr'
      path: '/demo/start/ssr/full-ssr'
      fullPath: '/demo/start/ssr/full-ssr'
      preLoaderRoute: typeof DemoStartSsrFullSsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/data-only': {
      id: '/demo/start/ssr/data-only'
      path: '/demo/start/ssr/data-only'
      fullPath: '/demo/start/ssr/data-only'
      preLoaderRoute: typeof DemoStartSsrDataOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiScheduleRequirementsRouteChildren {
  ApiScheduleRequirementsIdRoute: typeof ApiScheduleRequirementsIdRoute
}

const ApiScheduleRequirementsRouteChildren: ApiScheduleRequirementsRouteChildren =
  {
    ApiScheduleRequirementsIdRoute: ApiScheduleRequirementsIdRoute,
  }

const ApiScheduleRequirementsRouteWithChildren =
  ApiScheduleRequirementsRoute._addFileChildren(
    ApiScheduleRequirementsRouteChildren,
  )

interface ApiSchedulesRouteChildren {
  ApiSchedulesIdRoute: typeof ApiSchedulesIdRoute
}

const ApiSchedulesRouteChildren: ApiSchedulesRouteChildren = {
  ApiSchedulesIdRoute: ApiSchedulesIdRoute,
}

const ApiSchedulesRouteWithChildren = ApiSchedulesRoute._addFileChildren(
  ApiSchedulesRouteChildren,
)

interface ApiStaffRouteChildren {
  ApiStaffIdRoute: typeof ApiStaffIdRoute
}

const ApiStaffRouteChildren: ApiStaffRouteChildren = {
  ApiStaffIdRoute: ApiStaffIdRoute,
}

const ApiStaffRouteWithChildren = ApiStaffRoute._addFileChildren(
  ApiStaffRouteChildren,
)

interface ApiStaffAssignmentsRouteChildren {
  ApiStaffAssignmentsIdRoute: typeof ApiStaffAssignmentsIdRoute
}

const ApiStaffAssignmentsRouteChildren: ApiStaffAssignmentsRouteChildren = {
  ApiStaffAssignmentsIdRoute: ApiStaffAssignmentsIdRoute,
}

const ApiStaffAssignmentsRouteWithChildren =
  ApiStaffAssignmentsRoute._addFileChildren(ApiStaffAssignmentsRouteChildren)

interface ApiStaffConstraintsRouteChildren {
  ApiStaffConstraintsIdRoute: typeof ApiStaffConstraintsIdRoute
}

const ApiStaffConstraintsRouteChildren: ApiStaffConstraintsRouteChildren = {
  ApiStaffConstraintsIdRoute: ApiStaffConstraintsIdRoute,
}

const ApiStaffConstraintsRouteWithChildren =
  ApiStaffConstraintsRoute._addFileChildren(ApiStaffConstraintsRouteChildren)

interface ApiStaffSlotsRouteChildren {
  ApiStaffSlotsIdRoute: typeof ApiStaffSlotsIdRoute
}

const ApiStaffSlotsRouteChildren: ApiStaffSlotsRouteChildren = {
  ApiStaffSlotsIdRoute: ApiStaffSlotsIdRoute,
}

const ApiStaffSlotsRouteWithChildren = ApiStaffSlotsRoute._addFileChildren(
  ApiStaffSlotsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiScheduleRequirementsRoute: ApiScheduleRequirementsRouteWithChildren,
  ApiSchedulesRoute: ApiSchedulesRouteWithChildren,
  ApiStaffRoute: ApiStaffRouteWithChildren,
  ApiStaffAssignmentsRoute: ApiStaffAssignmentsRouteWithChildren,
  ApiStaffConstraintsRoute: ApiStaffConstraintsRouteWithChildren,
  ApiStaffSlotsRoute: ApiStaffSlotsRouteWithChildren,
  StaffIdRoute: StaffIdRoute,
  ScheduleRequirementsIndexRoute: ScheduleRequirementsIndexRoute,
  SchedulesIndexRoute: SchedulesIndexRoute,
  StaffAssignmentsIndexRoute: StaffAssignmentsIndexRoute,
  StaffConstraintsIndexRoute: StaffConstraintsIndexRoute,
  StaffSlotsIndexRoute: StaffSlotsIndexRoute,
  StaffIndexRoute: StaffIndexRoute,
  DemoApiNamesRoute: DemoApiNamesRoute,
  DemoStartApiRequestRoute: DemoStartApiRequestRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
  DemoStartSsrDataOnlyRoute: DemoStartSsrDataOnlyRoute,
  DemoStartSsrFullSsrRoute: DemoStartSsrFullSsrRoute,
  DemoStartSsrSpaModeRoute: DemoStartSsrSpaModeRoute,
  DemoStartSsrIndexRoute: DemoStartSsrIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
