/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StaffIndexRouteImport } from './routes/staff.index'
import { Route as SchedulesIndexRouteImport } from './routes/schedules.index'
import { Route as ScheduleRequirementsIndexRouteImport } from './routes/schedule-requirements.index'
import { Route as ApiStaffRouteImport } from './routes/api.staff'
import { Route as ApiSchedulesRouteImport } from './routes/api.schedules'
import { Route as ApiScheduleRequirementsRouteImport } from './routes/api.schedule-requirements'
import { Route as DemoStartServerFuncsRouteImport } from './routes/demo/start.server-funcs'
import { Route as DemoStartApiRequestRouteImport } from './routes/demo/start.api-request'
import { Route as DemoApiNamesRouteImport } from './routes/demo/api.names'
import { Route as ApiStaffIdRouteImport } from './routes/api.staff.$id'
import { Route as ApiSchedulesIdRouteImport } from './routes/api.schedules.$id'
import { Route as ApiScheduleRequirementsIdRouteImport } from './routes/api.schedule-requirements.$id'
import { Route as DemoStartSsrIndexRouteImport } from './routes/demo/start.ssr.index'
import { Route as DemoStartSsrSpaModeRouteImport } from './routes/demo/start.ssr.spa-mode'
import { Route as DemoStartSsrFullSsrRouteImport } from './routes/demo/start.ssr.full-ssr'
import { Route as DemoStartSsrDataOnlyRouteImport } from './routes/demo/start.ssr.data-only'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/staff/',
  path: '/staff/',
  getParentRoute: () => rootRouteImport,
} as any)
const SchedulesIndexRoute = SchedulesIndexRouteImport.update({
  id: '/schedules/',
  path: '/schedules/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRequirementsIndexRoute =
  ScheduleRequirementsIndexRouteImport.update({
    id: '/schedule-requirements/',
    path: '/schedule-requirements/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiStaffRoute = ApiStaffRouteImport.update({
  id: '/api/staff',
  path: '/api/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSchedulesRoute = ApiSchedulesRouteImport.update({
  id: '/api/schedules',
  path: '/api/schedules',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScheduleRequirementsRoute = ApiScheduleRequirementsRouteImport.update({
  id: '/api/schedule-requirements',
  path: '/api/schedule-requirements',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartServerFuncsRoute = DemoStartServerFuncsRouteImport.update({
  id: '/demo/start/server-funcs',
  path: '/demo/start/server-funcs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartApiRequestRoute = DemoStartApiRequestRouteImport.update({
  id: '/demo/start/api-request',
  path: '/demo/start/api-request',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiNamesRoute = DemoApiNamesRouteImport.update({
  id: '/demo/api/names',
  path: '/demo/api/names',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStaffIdRoute = ApiStaffIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiStaffRoute,
} as any)
const ApiSchedulesIdRoute = ApiSchedulesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiSchedulesRoute,
} as any)
const ApiScheduleRequirementsIdRoute =
  ApiScheduleRequirementsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => ApiScheduleRequirementsRoute,
  } as any)
const DemoStartSsrIndexRoute = DemoStartSsrIndexRouteImport.update({
  id: '/demo/start/ssr/',
  path: '/demo/start/ssr/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrSpaModeRoute = DemoStartSsrSpaModeRouteImport.update({
  id: '/demo/start/ssr/spa-mode',
  path: '/demo/start/ssr/spa-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrFullSsrRoute = DemoStartSsrFullSsrRouteImport.update({
  id: '/demo/start/ssr/full-ssr',
  path: '/demo/start/ssr/full-ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrDataOnlyRoute = DemoStartSsrDataOnlyRouteImport.update({
  id: '/demo/start/ssr/data-only',
  path: '/demo/start/ssr/data-only',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/schedule-requirements': typeof ApiScheduleRequirementsRouteWithChildren
  '/api/schedules': typeof ApiSchedulesRouteWithChildren
  '/api/staff': typeof ApiStaffRouteWithChildren
  '/schedule-requirements': typeof ScheduleRequirementsIndexRoute
  '/schedules': typeof SchedulesIndexRoute
  '/staff': typeof StaffIndexRoute
  '/api/schedule-requirements/$id': typeof ApiScheduleRequirementsIdRoute
  '/api/schedules/$id': typeof ApiSchedulesIdRoute
  '/api/staff/$id': typeof ApiStaffIdRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/schedule-requirements': typeof ApiScheduleRequirementsRouteWithChildren
  '/api/schedules': typeof ApiSchedulesRouteWithChildren
  '/api/staff': typeof ApiStaffRouteWithChildren
  '/schedule-requirements': typeof ScheduleRequirementsIndexRoute
  '/schedules': typeof SchedulesIndexRoute
  '/staff': typeof StaffIndexRoute
  '/api/schedule-requirements/$id': typeof ApiScheduleRequirementsIdRoute
  '/api/schedules/$id': typeof ApiSchedulesIdRoute
  '/api/staff/$id': typeof ApiStaffIdRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/schedule-requirements': typeof ApiScheduleRequirementsRouteWithChildren
  '/api/schedules': typeof ApiSchedulesRouteWithChildren
  '/api/staff': typeof ApiStaffRouteWithChildren
  '/schedule-requirements/': typeof ScheduleRequirementsIndexRoute
  '/schedules/': typeof SchedulesIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/api/schedule-requirements/$id': typeof ApiScheduleRequirementsIdRoute
  '/api/schedules/$id': typeof ApiSchedulesIdRoute
  '/api/staff/$id': typeof ApiStaffIdRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/schedule-requirements'
    | '/api/schedules'
    | '/api/staff'
    | '/schedule-requirements'
    | '/schedules'
    | '/staff'
    | '/api/schedule-requirements/$id'
    | '/api/schedules/$id'
    | '/api/staff/$id'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/schedule-requirements'
    | '/api/schedules'
    | '/api/staff'
    | '/schedule-requirements'
    | '/schedules'
    | '/staff'
    | '/api/schedule-requirements/$id'
    | '/api/schedules/$id'
    | '/api/staff/$id'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  id:
    | '__root__'
    | '/'
    | '/api/schedule-requirements'
    | '/api/schedules'
    | '/api/staff'
    | '/schedule-requirements/'
    | '/schedules/'
    | '/staff/'
    | '/api/schedule-requirements/$id'
    | '/api/schedules/$id'
    | '/api/staff/$id'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiScheduleRequirementsRoute: typeof ApiScheduleRequirementsRouteWithChildren
  ApiSchedulesRoute: typeof ApiSchedulesRouteWithChildren
  ApiStaffRoute: typeof ApiStaffRouteWithChildren
  ScheduleRequirementsIndexRoute: typeof ScheduleRequirementsIndexRoute
  SchedulesIndexRoute: typeof SchedulesIndexRoute
  StaffIndexRoute: typeof StaffIndexRoute
  DemoApiNamesRoute: typeof DemoApiNamesRoute
  DemoStartApiRequestRoute: typeof DemoStartApiRequestRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
  DemoStartSsrDataOnlyRoute: typeof DemoStartSsrDataOnlyRoute
  DemoStartSsrFullSsrRoute: typeof DemoStartSsrFullSsrRoute
  DemoStartSsrSpaModeRoute: typeof DemoStartSsrSpaModeRoute
  DemoStartSsrIndexRoute: typeof DemoStartSsrIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/': {
      id: '/staff/'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedules/': {
      id: '/schedules/'
      path: '/schedules'
      fullPath: '/schedules'
      preLoaderRoute: typeof SchedulesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule-requirements/': {
      id: '/schedule-requirements/'
      path: '/schedule-requirements'
      fullPath: '/schedule-requirements'
      preLoaderRoute: typeof ScheduleRequirementsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/staff': {
      id: '/api/staff'
      path: '/api/staff'
      fullPath: '/api/staff'
      preLoaderRoute: typeof ApiStaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/schedules': {
      id: '/api/schedules'
      path: '/api/schedules'
      fullPath: '/api/schedules'
      preLoaderRoute: typeof ApiSchedulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/schedule-requirements': {
      id: '/api/schedule-requirements'
      path: '/api/schedule-requirements'
      fullPath: '/api/schedule-requirements'
      preLoaderRoute: typeof ApiScheduleRequirementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/api-request': {
      id: '/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof DemoStartApiRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/names': {
      id: '/demo/api/names'
      path: '/demo/api/names'
      fullPath: '/demo/api/names'
      preLoaderRoute: typeof DemoApiNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/staff/$id': {
      id: '/api/staff/$id'
      path: '/$id'
      fullPath: '/api/staff/$id'
      preLoaderRoute: typeof ApiStaffIdRouteImport
      parentRoute: typeof ApiStaffRoute
    }
    '/api/schedules/$id': {
      id: '/api/schedules/$id'
      path: '/$id'
      fullPath: '/api/schedules/$id'
      preLoaderRoute: typeof ApiSchedulesIdRouteImport
      parentRoute: typeof ApiSchedulesRoute
    }
    '/api/schedule-requirements/$id': {
      id: '/api/schedule-requirements/$id'
      path: '/$id'
      fullPath: '/api/schedule-requirements/$id'
      preLoaderRoute: typeof ApiScheduleRequirementsIdRouteImport
      parentRoute: typeof ApiScheduleRequirementsRoute
    }
    '/demo/start/ssr/': {
      id: '/demo/start/ssr/'
      path: '/demo/start/ssr'
      fullPath: '/demo/start/ssr'
      preLoaderRoute: typeof DemoStartSsrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/spa-mode': {
      id: '/demo/start/ssr/spa-mode'
      path: '/demo/start/ssr/spa-mode'
      fullPath: '/demo/start/ssr/spa-mode'
      preLoaderRoute: typeof DemoStartSsrSpaModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/full-ssr': {
      id: '/demo/start/ssr/full-ssr'
      path: '/demo/start/ssr/full-ssr'
      fullPath: '/demo/start/ssr/full-ssr'
      preLoaderRoute: typeof DemoStartSsrFullSsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/data-only': {
      id: '/demo/start/ssr/data-only'
      path: '/demo/start/ssr/data-only'
      fullPath: '/demo/start/ssr/data-only'
      preLoaderRoute: typeof DemoStartSsrDataOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiScheduleRequirementsRouteChildren {
  ApiScheduleRequirementsIdRoute: typeof ApiScheduleRequirementsIdRoute
}

const ApiScheduleRequirementsRouteChildren: ApiScheduleRequirementsRouteChildren =
  {
    ApiScheduleRequirementsIdRoute: ApiScheduleRequirementsIdRoute,
  }

const ApiScheduleRequirementsRouteWithChildren =
  ApiScheduleRequirementsRoute._addFileChildren(
    ApiScheduleRequirementsRouteChildren,
  )

interface ApiSchedulesRouteChildren {
  ApiSchedulesIdRoute: typeof ApiSchedulesIdRoute
}

const ApiSchedulesRouteChildren: ApiSchedulesRouteChildren = {
  ApiSchedulesIdRoute: ApiSchedulesIdRoute,
}

const ApiSchedulesRouteWithChildren = ApiSchedulesRoute._addFileChildren(
  ApiSchedulesRouteChildren,
)

interface ApiStaffRouteChildren {
  ApiStaffIdRoute: typeof ApiStaffIdRoute
}

const ApiStaffRouteChildren: ApiStaffRouteChildren = {
  ApiStaffIdRoute: ApiStaffIdRoute,
}

const ApiStaffRouteWithChildren = ApiStaffRoute._addFileChildren(
  ApiStaffRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiScheduleRequirementsRoute: ApiScheduleRequirementsRouteWithChildren,
  ApiSchedulesRoute: ApiSchedulesRouteWithChildren,
  ApiStaffRoute: ApiStaffRouteWithChildren,
  ScheduleRequirementsIndexRoute: ScheduleRequirementsIndexRoute,
  SchedulesIndexRoute: SchedulesIndexRoute,
  StaffIndexRoute: StaffIndexRoute,
  DemoApiNamesRoute: DemoApiNamesRoute,
  DemoStartApiRequestRoute: DemoStartApiRequestRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
  DemoStartSsrDataOnlyRoute: DemoStartSsrDataOnlyRoute,
  DemoStartSsrFullSsrRoute: DemoStartSsrFullSsrRoute,
  DemoStartSsrSpaModeRoute: DemoStartSsrSpaModeRoute,
  DemoStartSsrIndexRoute: DemoStartSsrIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
